// WindowsSharp
//
// Copyright (C) 2021 Ronald van Manen <rvanmanen@gmail.com>
//
// MIT License
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

namespace WindowsSharp.Interop
{
    /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE"]/*' />
    public enum DISPLAYCONFIG_DEVICE_INFO_TYPE
    {
        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME = 1,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME = 2,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE = 3,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME = 4,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE = 5,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_BASE_TYPE"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_BASE_TYPE = 6,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_GET_SUPPORT_VIRTUAL_RESOLUTION"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_GET_SUPPORT_VIRTUAL_RESOLUTION = 7,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_SET_SUPPORT_VIRTUAL_RESOLUTION"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_SET_SUPPORT_VIRTUAL_RESOLUTION = 8,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO = 9,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_SET_ADVANCED_COLOR_STATE"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_SET_ADVANCED_COLOR_STATE = 10,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_GET_SDR_WHITE_LEVEL"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_GET_SDR_WHITE_LEVEL = 11,

        /// <include file='DISPLAYCONFIG_DEVICE_INFO_TYPE.xml' path='doc/member[@name="DISPLAYCONFIG_DEVICE_INFO_TYPE.DISPLAYCONFIG_DEVICE_INFO_FORCE_UINT32"]/*' />
        DISPLAYCONFIG_DEVICE_INFO_FORCE_UINT32 = unchecked((int)(0xFFFFFFFF)),
    }
}
