// This file is part of WindowsSharp
//
// Copyright (C) 2021-2023 Ronald van Manen <rvanmanen@gmail.com>
//
// MIT License
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED *AS IS*, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

namespace WindowsSharp.Interop
{
    /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS"]/*' />
    public enum D3D11_CONTENT_PROTECTION_CAPS
    {
        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_SOFTWARE"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_SOFTWARE = 0x1,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_HARDWARE"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_HARDWARE = 0x2,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_PROTECTION_ALWAYS_ON"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_PROTECTION_ALWAYS_ON = 0x4,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_PARTIAL_DECRYPTION"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_PARTIAL_DECRYPTION = 0x8,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_CONTENT_KEY"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_CONTENT_KEY = 0x10,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_FRESHEN_SESSION_KEY"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_FRESHEN_SESSION_KEY = 0x20,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_ENCRYPTED_READ_BACK"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_ENCRYPTED_READ_BACK = 0x40,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_ENCRYPTED_READ_BACK_KEY"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_ENCRYPTED_READ_BACK_KEY = 0x80,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_SEQUENTIAL_CTR_IV"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_SEQUENTIAL_CTR_IV = 0x100,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_ENCRYPT_SLICEDATA_ONLY"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_ENCRYPT_SLICEDATA_ONLY = 0x200,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_DECRYPTION_BLT"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_DECRYPTION_BLT = 0x400,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_PROTECT_UNCOMPRESSED"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_PROTECT_UNCOMPRESSED = 0x800,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_PROTECTED_MEMORY_PAGEABLE"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_PROTECTED_MEMORY_PAGEABLE = 0x1000,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_TEARDOWN"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_TEARDOWN = 0x2000,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_DRM_COMMUNICATION"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_DRM_COMMUNICATION = 0x4000,

        /// <include file='D3D11_CONTENT_PROTECTION_CAPS.xml' path='doc/member[@name="D3D11_CONTENT_PROTECTION_CAPS.D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_DRM_COMMUNICATION_MULTI_THREADED"]/*' />
        D3D11_CONTENT_PROTECTION_CAPS_HARDWARE_DRM_COMMUNICATION_MULTI_THREADED = 0x8000,
    }
}
